export const FETCH_USERS = {
  REQUEST: "FETCH_USERS_REQUEST",
  SUCCESS: "FETCH_USERS_SUCCESS",
  FAILURE: "FETCH_USERS_FAILURE",
};

export const ADD_USER = {
  REQUEST: "ADD_USER_REQUEST",
  SUCCESS: "ADD_USER_SUCCESS",
  FAILURE: "ADD_USER_FAILURE",
};

export const DELETE_USER = {
  REQUEST: "DELETE_USER_REQUEST",
  SUCCESS: "DELETE_USER_SUCCESS",
  FAILURE: "DELETE_USER_FAILURE",
};

export const TABLE_CONTROLS = {
  SET_PAGE: "SET_PAGE",
  SET_LIMIT: "SET_LIMIT",
  SET_SEARCH: "SET_SEARCH",
  SET_SORT_BY: "SET_SORT_BY",
  SET_ORDER: "SET_ORDER",
  TOGGLE_SORT: "TOGGLE_SORT",
};

export const CLEAR_ACTION_ERROR = "CLEAR_ACTION_ERROR";

export const AUTH = {
  LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",
  LOGOUT: "AUTH_LOGOUT",
};export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
